services:
  greenbids-tailor:
    image: ghcr.io/greenbids/tailor:0.2.4
    environment:
      - WEB_CONCURRENCY=1
      - GREENBIDS_TAILOR_MODEL_NAME=None
    restart: unless-stopped
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M

  load_balancer:
    image: nginx:latest
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - greenbids-tailor
    ports:
      - 8000:8000
