apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greenbids-tailor.fullname" . }}-envs
  labels:
    {{- include "greenbids-tailor.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k | quote }}: {{ $v | toString | quote }}
  {{- end }}
