apiVersion: v1
kind: Service
metadata:
  name: {{ include "greenbids-tailor.fullname" . }}
  labels:
    {{- include "greenbids-tailor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.env.OTEL_EXPORTER_PROMETHEUS_ENABLED }}
    - port: {{ .Values.env.OTEL_EXPORTER_PROMETHEUS_PORT | default 9464 }}
      targetPort: http
      protocol: TCP
      name: prom
    {{- end }}
  selector:
    {{- include "greenbids-tailor.selectorLabels" . | nindent 4 }}
