name: Create and publish a Helm Chart

on:
  workflow_call:
    inputs:
      app-version:
        type: string
        description: Version number of the packaged application
        required: true
      version:
        type: string
        description: Version number of the image and chart
        required: true
  workflow_dispatch:
    inputs:
      app-version:
          type: string
          description: Version number of the packaged application
          required: true
      version:
          type: string
          description: Version number of the image and chart
          required: true

env:
  REGISTRY: ghcr.io
  CHART_NAMESPACE: greenbids/charts
  CHART_NAME: tailor

jobs:
  build-and-push:
    runs-on:
      - ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: |
            helm package --version ${{ inputs.version }} --app-version ${{ inputs.app-version }} chart/
      - name: Push
        if: github.event_type == 'push'
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: |
            helm push ${{ env.CHART_NAME }}-${{ inputs.VERSION }}.tgz oci://${{ env.REGISTRY }}/${{ env.CHART_NAMESPACE }}
