name: Create and publish a Helm Chart

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: Version number of the image and chart
        required: true
  workflow_dispatch:
    inputs:
      version:
          type: string
          description: Version number of the image and chart
          required: true

env:
  REGISTRY: ghcr.io
  CHART_NAMESPACE: greenbids/charts
  CHART_NAME: tailor

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Package
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: |
            helm package --version ${{ inputs.version }} --app-version ${{ inputs.version }} chart/
      - uses: actions/upload-artifact@v4
        with:
          name: chart
          path: ${{ env.CHART_NAME }}-${{ inputs.version }}.tgz
  push:
    if: github.event_name == 'push'
    needs: build
    environment:
      name: chart-repository
      url: http://${{ env.REGISTRY }}/${{ env.CHART_NAMESPACE }}/${{ env.CHART_NAME }}
    runs-on:
      - ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: chart
          path: "."
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: |
            helm push ${{ env.CHART_NAME }}-${{ inputs.version }}.tgz oci://${{ env.REGISTRY }}/${{ env.CHART_NAMESPACE }}
