name: Generate documentation page

on:
  push:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  openapi:
    runs-on:
        - ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build package
        working-directory: python
        run: pip wheel --no-deps -w dist .
      - name: Install package
        working-directory: python
        run: pip install dist/*.whl
      - name: OpenAPI spec generation
        run: python -c 'from greenbids.tailor.core.app import app; import json; print(json.dumps(app.openapi()))' > openapi.json
      - name: Save OpenAPI spec
        id: cache-openapi-save
        uses: actions/cache/save@v4
        with:
          path: |
            openapi.json
          key: openapi-${{ github.sha }}
  build:
    needs: openapi
    runs-on:
      - ubuntu-latest
    steps:
      - name: Restore OpenAPI spec
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            openapi.json
          key: openapi-${{ github.sha }}
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swagger-ui

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
