name: Create and publish Python package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install build tool
        uses: pypa/hatch@install
      - name: Build wheel
        working-directory: python
        run: hatch build -t wheel
      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: python/dist/

  publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    env:
      pypi_url: ${{ startsWith(github.ref, 'refs/tags/') && 'https://pypi.org' || 'https://test.pypi.org' }}
      pypi_path: ${{ startsWith(github.ref, 'refs/tags/') && '/simple/' || '/legacy/' }}
    environment:
      name: ${{ startsWith(github.ref, 'refs/tags/') && 'pypi' || 'testpypi' }}
      url: "${{ env.pypi_url }}/p/greenbids-tailor"
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ env.pypi_url }}${{ env.pypi_path }}
