name: Create and publish Python package

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install build tool
        uses: pypa/hatch@install
      - name: Get default version
        id: default_version
        working-directory: python
        run: echo "version=$(hatch version)" | tee -a "$GITHUB_OUTPUT"
      - name: Version update
        id: version
        env:
          PRE_RELEASE: ${{ github.event_name == 'pull_request' && format('.a{0}', github.event.pull_request.number) || '' }}
          PEP440_REGEX: >-
            (?P<epoch>([0-9]+!)?)(?P<release>[0-9]+(\.[0-9]+)*)(?P<pre>((a|b|rc)[0-9]+)?)(?P<post>(\.post[0-9]+)?)(?P<dev>(\.dev[0-9]+)?)(.*)
        run: |
          python -c '
          import re
          print(re.sub(r"'$PEP440_REGEX'", r"version=\g<epoch>\g<release>'${PRE_RELEASE}'\g<post>\g<dev>", "${{ steps.default_version.outputs.version }}"))
          ' | tee -a "$GITHUB_OUTPUT"
      - name: Build wheel
        working-directory: python
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.version.outputs.version }}
        run: hatch build -t wheel
      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: python/dist/

  publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    env:
      pypi_url: ${{ startsWith(github.ref, 'refs/tags/') && 'https://pypi.org' || 'https://test.pypi.org' }}
      pypi_path: ${{ startsWith(github.ref, 'refs/tags/') && '/simple/' || '/legacy/' }}
    environment:
      name: ${{ startsWith(github.ref, 'refs/tags/') && 'pypi' || 'testpypi' }}
      url: "${{ env.pypi_url }}/p/greenbids-tailor"
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ env.pypi_url }}${{ env.pypi_path }}
